pull_request_rules:
  - name: Automatic merge on approval
    conditions:
        - "#review-requested=0"
        - "#changes-requested-reviews-by=0"
    actions:
      merge:
        method: merge
        strict: smart+fasttrack
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch:
        force: false
  - name: Bypass for repo owner
    conditions:
      - author~=^ARMmaster17$
    actions:
      review:
        type: APPROVE
        message: Bypass review
  - name: Bypass for Bots
    conditions:
      - author~=^renovate\[bot\]$
    actions:
      review:
        type: APPROVE
        message: Automatic bot approval
