nameservers:
  - 10.1.0.4
  - 8.8.8.8
template: pve-img:vztmpl/debian-10-standard_10.7-1_amd64.tar.gz
bridge: internal
cidr: 24
gateway: 10.0.0.1
mtu: 1450
domain: firecore.lab
disk_store: pve-storage
autostart: 1