name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13

    - name: Build
      run: make build

    - name: Test
      run: make test
      env:
        CAPTAIN_DRY_RUN: TRUE
        CAPTAIN_DB: test.db

    - name: Publish code coverage
      uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: c19b466b4c3e08a48f23e2c883a52c68bc7b2a3b2f52ab914224004b5a990df3
      with:
        prefix: github.com/ARMmaster17/Captain
        coverageLocations: ${{github.workspace}}/cover.out:gocov

    - name: DEBUG tree layout
      run: tree

    - name: Publish unit test results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: report.xml
        report_individual_runs: "true"
