name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_CONN: sqlite3-file
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
    
    - name: Create configuration directory
      run: sudo mkdir /etc/captain && sudo chmod 777 /etc/captain

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
