name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.13

    - name: Test ATC
      run: cd ATC; make test
      env:
        CAPTAIN_DRY_RUN: TRUE
        CAPTAIN_DB: testing.db

    - name: Test CaptainLib
      run: cd CaptainLib; make test

    - name: Test Radar (Go)
      run: cd Radar; make test

    - name: Test Shared
      run: cd Shared; make test

    - name: Test Builder
      run: cd Builder; make test

    - name: Publish code coverage
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: c19b466b4c3e08a48f23e2c883a52c68bc7b2a3b2f52ab914224004b5a990df3
      with:
        prefix: github.com/ARMmaster17/Captain
        coverageLocations: ${{github.workspace}}/*/cover.out:gocov

    - name: Publish unit test results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: ./*/report.xml
        report_individual_runs: "true"

    - name: Build ATC RPM
      run: cd ATC; make captain-atc.deb

    - name: Build Radar RPM
      run: cd Radar; make captain-radar.deb

    - name: Upload RPMs
      uses: actions/upload-artifact@v2
      with:
        name: DEB Packages
        path: ./**/*.deb
        retention-days: 3
