name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_CONN: sqlite3-file
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
    
    - name: Create configuration directory
      run: sudo mkdir /etc/captain && sudo chmod 777 /etc/captain

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -coverprofile=cover.out ./...

    - name: Publish code coverage
      uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: c19b466b4c3e08a48f23e2c883a52c68bc7b2a3b2f52ab914224004b5a990df3
      with:
        prefix: github.com/ARMmaster17/Captain
        debug: true
        coverageLocations: |
          ${{github.workspace}}/cover.out:gocov
